const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Mouse,
		C3.Behaviors.Flash,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SubVar,
		C3.JavaScriptInEvents.FolhaDeEventosFase1_Event9_Act1,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.JavaScriptInEvents.FolhaDeEventosFase2_Event9_Act1,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Âncora: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Teclado: 0},
	{entrouboss: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Plataforma: 0},
	{Wizard: 0},
	{Sólido: 0},
	{bloco6: 0},
	{bloco1: 0},
	{fundoParteDeBaixo: 0},
	{bloco2: 0},
	{bloco3: 0},
	{bloco4: 0},
	{bloco5: 0},
	{fundoComeço: 0},
	{bloco7: 0},
	{rampa1: 0},
	{rampa2: 0},
	{seguindoRampa: 0},
	{PularAtravés: 0},
	{pedraFlutuante: 0},
	{pedra: 0},
	{platafroma1: 0},
	{plataforma2: 0},
	{plataforma3: 0},
	{plataforma4: 0},
	{plataforma5: 0},
	{espinhos: 0},
	{bloco8: 0},
	{bloco9: 0},
	{bloco10: 0},
	{bloco11: 0},
	{bloco12: 0},
	{bloco13: 0},
	{bloco14: 0},
	{bloco15: 0},
	{bloco16: 0},
	{bloco17: 0},
	{bloco18: 0},
	{bloco19: 0},
	{bloco20: 0},
	{bloco21: 0},
	{bloco22: 0},
	{fundoFinal: 0},
	{pedrasGrandes1: 0},
	{pedrasGrandes2: 0},
	{Luz: 0},
	{planoDeFundoFase2: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Senóide: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{feitiço: 0},
	{Mouse: 0},
	{Direcao: 0},
	{Piscar: 0},
	{Sprite15: 0},
	{SensorGosmaDireita: 0},
	{SensorGosmaEsquerda: 0},
	{vidasboss: 0},
	{Sprite16: 0},
	{SensorBoss: 0},
	{feitiçoboss: 0},
	{barravidas: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{JogarNovamenteTXT: 0},
	{FundoInicio: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{BotaoJogarInicio: 0},
	{VoltarInicioTXT: 0},
	{Cristal: 0},
	{FonteDeSprites: 0},
	{TextoCristais: 0},
	{CristalPontos: 0},
	{Áudio: 0},
	{FundoVitoria: 0},
	{CristalFinal: 0},
	{vidas: 0},
	{Cristais: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Teclado: class extends self.IInstance {},
	Wizard: class extends self.ISpriteInstance {},
	bloco6: class extends self.ISpriteInstance {},
	bloco1: class extends self.ISpriteInstance {},
	fundoParteDeBaixo: class extends self.ISpriteInstance {},
	bloco2: class extends self.ISpriteInstance {},
	bloco3: class extends self.ISpriteInstance {},
	bloco4: class extends self.ISpriteInstance {},
	bloco5: class extends self.ISpriteInstance {},
	fundoComeço: class extends self.ISpriteInstance {},
	bloco7: class extends self.ISpriteInstance {},
	rampa1: class extends self.ISpriteInstance {},
	rampa2: class extends self.ISpriteInstance {},
	seguindoRampa: class extends self.ISpriteInstance {},
	pedraFlutuante: class extends self.ISpriteInstance {},
	pedra: class extends self.ISpriteInstance {},
	platafroma1: class extends self.ISpriteInstance {},
	plataforma2: class extends self.ISpriteInstance {},
	plataforma3: class extends self.ISpriteInstance {},
	plataforma4: class extends self.ISpriteInstance {},
	plataforma5: class extends self.ISpriteInstance {},
	espinhos: class extends self.ISpriteInstance {},
	bloco8: class extends self.ISpriteInstance {},
	bloco9: class extends self.ISpriteInstance {},
	bloco10: class extends self.ISpriteInstance {},
	bloco11: class extends self.ISpriteInstance {},
	bloco12: class extends self.ISpriteInstance {},
	bloco13: class extends self.ISpriteInstance {},
	bloco14: class extends self.ISpriteInstance {},
	bloco15: class extends self.ISpriteInstance {},
	bloco16: class extends self.ISpriteInstance {},
	bloco17: class extends self.ISpriteInstance {},
	bloco18: class extends self.ISpriteInstance {},
	bloco19: class extends self.ISpriteInstance {},
	bloco20: class extends self.ISpriteInstance {},
	bloco21: class extends self.ISpriteInstance {},
	bloco22: class extends self.ISpriteInstance {},
	fundoFinal: class extends self.ISpriteInstance {},
	pedrasGrandes1: class extends self.ISpriteInstance {},
	pedrasGrandes2: class extends self.ISpriteInstance {},
	Luz: class extends self.ISpriteInstance {},
	planoDeFundoFase2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	feitiço: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	SensorGosmaDireita: class extends self.ISpriteInstance {},
	SensorGosmaEsquerda: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	SensorBoss: class extends self.ISpriteInstance {},
	feitiçoboss: class extends self.ISpriteInstance {},
	barravidas: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	JogarNovamenteTXT: class extends self.ISpriteFontInstance {},
	FundoInicio: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	BotaoJogarInicio: class extends self.ISpriteFontInstance {},
	VoltarInicioTXT: class extends self.ISpriteFontInstance {},
	Cristal: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	TextoCristais: class extends self.ITextInstance {},
	CristalPontos: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	FundoVitoria: class extends self.ISpriteInstance {},
	CristalFinal: class extends self.ISpriteInstance {}
}